// <auto-generated />
using System;
using System.Collections.Generic;
using Covoiturage_La_Cite_Server_Core_.Data.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Covoiturage_La_Cite_Server_Core_.Data.PostgreSQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Affinity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AffinityScore")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AvgRatingGiven")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AvgRatingReceived")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FavoriteSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HadIncident")
                        .HasColumnType("boolean");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActuallyFavorite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastTripDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalTripsTogether")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("UserId", "TargetUserId")
                        .IsUnique();

                    b.ToTable("Affinities");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("text");

                    b.Property<string>("PreviousValueJson")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.ChallengeParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("EcoChallengeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RewardClaimed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EcoChallengeId");

                    b.HasIndex("UserId", "EcoChallengeId")
                        .IsUnique();

                    b.ToTable("ChallengeParticipations");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.DriverDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DriverProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverProfileId");

                    b.ToTable("DriverDocuments");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.DriverProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BalanceAvailable")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BalancePenalties")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BalancePending")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CancellationRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Co2SavedKg")
                        .HasColumnType("numeric");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("integer");

                    b.Property<int>("PunctualityScore")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("TotalTripsAsDriver")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ValidatedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WithholdingRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DriverProfiles");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.EcoChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ActiveUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RewardBadgeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("integer");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RewardBadgeId");

                    b.ToTable("EcoChallenges");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.GeofenceZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Point>("CenterPoint")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<Polygon>("Polygon")
                        .HasColumnType("geography (polygon, 4326)");

                    b.Property<decimal>("RadiusMeters")
                        .HasColumnType("numeric");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GeofenceZones");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.GpsPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AccuracyMeters")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HeadingDegrees")
                        .HasColumnType("numeric");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)");

                    b.Property<decimal>("SpeedKmh")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TripId", "CapturedAt");

                    b.ToTable("GpsPositions");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.MatchingScoreCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AffinityScore")
                        .HasColumnType("integer");

                    b.Property<int>("ArrivalProximityScore")
                        .HasColumnType("integer");

                    b.Property<int>("Bonuses")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartureProximityScore")
                        .HasColumnType("integer");

                    b.Property<int>("GlobalScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PreferenceScore")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TripId", "PassengerId")
                        .IsUnique();

                    b.ToTable("MatchingScoreCaches");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeepLink")
                        .HasColumnType("text");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<bool?>("PushDelivered")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("PushSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RelatedReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedTripId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Penalty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminDecision")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ContestDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContestReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeductedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GoScoreImpact")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggerReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.PlatformConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("PlatformConfigs");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.PlatformStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveUsersLast30Days")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PendingDriverApplications")
                        .HasColumnType("integer");

                    b.Property<int>("PendingReports")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCo2SavedKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalRevenuePlatform")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("integer");

                    b.Property<int>("TripsThisMonth")
                        .HasColumnType("integer");

                    b.Property<int>("TripsToday")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PlatformStats");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<Guid?>("AssignedAdminId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoPrevBlockUser")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("EvidenceUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("GpsTraceSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("PublicReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReportedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PublicReference")
                        .IsUnique();

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("TripId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("BoardingConfirmedByDriver")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BoardingConfirmedByPassenger")
                        .HasColumnType("boolean");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompatibilityScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("PassengerActuallyBoarded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PassengerMessage")
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerSeat")
                        .HasColumnType("numeric");

                    b.Property<string>("RefusalReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TripId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevieweeRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TripId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Security.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BlockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpCodeHash")
                        .HasColumnType("text");

                    b.Property<int>("OtpCurrentAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OtpResendCount")
                        .HasColumnType("integer");

                    b.Property<int>("OtpTotalAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IdKeyHash")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("AuthSessions");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Security.CertificateRotationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AffectedClientsCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NewPublicKeyGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PropagationCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CertificateRotationEvents");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Security.ClientCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CooldownUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CurrentKeyIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentPublicKeyPem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedValidationCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasGotNewPublicKey")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSuccessfulRequestAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PreviousKeyRetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousPublicKeyPem")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresServiceDesk")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceFingerprint")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ClientCertificates");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Security.UserSecurityActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnomalyType")
                        .HasColumnType("text");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<string>("GeoLocation")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestOrigin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsedKeyVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WasAnomaly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("UserSecurityActivities");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Security.WebSessionKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServerSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("WebSessionKeys");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.SmartSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedTripId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ShownAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuggestedArrival")
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("SuggestedDays")
                        .HasColumnType("integer[]");

                    b.Property<string>("SuggestedDeparture")
                        .HasColumnType("text");

                    b.Property<string>("SuggestedTimeWindow")
                        .HasColumnType("text");

                    b.Property<string>("SuggestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SmartSuggestions");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.SosAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AdminContactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmergencyContactsNotified")
                        .HasColumnType("boolean");

                    b.Property<string>("EmergencyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GpsSnapshotJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("TriggerLocation")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("SosAlerts");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DriverShare")
                        .HasColumnType("numeric");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PenaltyDeducted")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PlatformShare")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("PreAuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActualCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ArrivalAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArrivalLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("ArrivalPoint")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("numeric");

                    b.Property<bool>("BaggageAllowed")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Co2SavedKg")
                        .HasColumnType("numeric");

                    b.Property<string>("ConversationLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPassengers")
                        .HasColumnType("integer");

                    b.Property<string>("DepartureAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<string>("DepartureLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("DeparturePoint")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("DriverNote")
                        .HasColumnType("text");

                    b.Property<Guid?>("DriverProfileId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("EstimatedArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("EstimatedDistanceKm")
                        .HasColumnType("numeric");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPassengers")
                        .HasColumnType("integer");

                    b.Property<bool>("MusicAllowed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentTripId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PassengerPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Polyline")
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerPassenger")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<int[]>("RecurrenceDays")
                        .HasColumnType("integer[]");

                    b.Property<DateOnly?>("RecurrenceEndDate")
                        .HasColumnType("date");

                    b.Property<bool>("SmokingAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartureDate");

                    b.HasIndex("DriverId");

                    b.HasIndex("DriverProfileId");

                    b.HasIndex("ParentTripId");

                    b.HasIndex("Status");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlreadySetAProfilePicture")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlreadySignPolitics")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlreadySubmittedAllVehiculeDocument")
                        .HasColumnType("boolean");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<bool>("CanBeDriver")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GoScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProfileVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MicrosoftSsoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SuspendedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MicrosoftSsoId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.UserBehaviorPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgSessionsPerWeek")
                        .HasColumnType("numeric");

                    b.Property<string>("ChurnRisk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastTripDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MostFrequentArrival")
                        .HasColumnType("text");

                    b.Property<string>("MostFrequentDeparture")
                        .HasColumnType("text");

                    b.Property<decimal>("PatternConfidence")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("RecomputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("TypicalDepartureDays")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<TimeOnly?>("TypicalDepartureTimeEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("TypicalDepartureTimeStart")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserBehaviorPatterns");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConversationLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPets")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MusicAccepted")
                        .HasColumnType("boolean");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("SmokesRegularly")
                        .HasColumnType("boolean");

                    b.Property<bool>("TypicalBaggage")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.UserStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageRatingAsDriver")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageRatingAsPassenger")
                        .HasColumnType("numeric");

                    b.Property<int>("BadgesCount")
                        .HasColumnType("integer");

                    b.Property<int>("ChallengesCompleted")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastTripDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RecomputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCo2SavedKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDistanceKm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalEarningsDriver")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalPenalties")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReviewsGiven")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReviewsReceived")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalSpentPassenger")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalTripsAsDriver")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTripsAsPassenger")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("VehiclePhotoUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverProfileId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.WaypointTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("WaypointTrips");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Withdrawal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DriverProfileId");

                    b.ToTable("Withdrawals");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Affinity", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.ChallengeParticipation", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.EcoChallenge", "EcoChallenge")
                        .WithMany("Participations")
                        .HasForeignKey("EcoChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EcoChallenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.DriverDocument", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.DriverProfile", "DriverProfile")
                        .WithMany("Documents")
                        .HasForeignKey("DriverProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverProfile");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.DriverProfile", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithOne("DriverProfile")
                        .HasForeignKey("Covoiturage_La_Cite_Server_Core_.Domain.Entities.DriverProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.EcoChallenge", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Badge", "RewardBadge")
                        .WithMany()
                        .HasForeignKey("RewardBadgeId");

                    b.Navigation("RewardBadge");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.GpsPosition", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", "Trip")
                        .WithMany("GpsPositions")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.MatchingScoreCache", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Penalty", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId");

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId");

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany("Penalties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Report", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "Reporter")
                        .WithMany("ReportsFiled")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "Passenger")
                        .WithMany("Reservations")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", "Trip")
                        .WithMany("Reservations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Review", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Reservation", "Reservation")
                        .WithOne("Review")
                        .HasForeignKey("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Review", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "Reviewee")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "Reviewer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", "Trip")
                        .WithMany("Reviews")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Security.ClientCertificate", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Security.UserSecurityActivity", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Security.ClientCertificate", "Certificate")
                        .WithMany("SecurityActivities")
                        .HasForeignKey("CertificateId");

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Security.WebSessionKey", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.SmartSuggestion", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.SosAlert", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany("SosAlerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Transactions")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Passenger");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.DriverProfile", null)
                        .WithMany("Trips")
                        .HasForeignKey("DriverProfileId");

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", "ParentTrip")
                        .WithMany("RecurringInstances")
                        .HasForeignKey("ParentTripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("ParentTrip");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.UserBehaviorPattern", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Covoiturage_La_Cite_Server_Core_.Domain.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.UserStat", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", "User")
                        .WithOne("Stats")
                        .HasForeignKey("Covoiturage_La_Cite_Server_Core_.Domain.Entities.UserStat", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.DriverProfile", "DriverProfile")
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverProfile");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.WaypointTrip", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", "Trip")
                        .WithMany("Waypoints")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Withdrawal", b =>
                {
                    b.HasOne("Covoiturage_La_Cite_Server_Core_.Domain.Entities.DriverProfile", "DriverProfile")
                        .WithMany()
                        .HasForeignKey("DriverProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverProfile");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.DriverProfile", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Trips");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.EcoChallenge", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Review");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Security.ClientCertificate", b =>
                {
                    b.Navigation("SecurityActivities");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Trip", b =>
                {
                    b.Navigation("GpsPositions");

                    b.Navigation("RecurringInstances");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");

                    b.Navigation("Waypoints");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.User", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("DriverProfile");

                    b.Navigation("Notifications");

                    b.Navigation("Penalties");

                    b.Navigation("Preferences");

                    b.Navigation("ReportsFiled");

                    b.Navigation("Reservations");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("SosAlerts");

                    b.Navigation("Stats");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Covoiturage_La_Cite_Server_Core_.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
