export * from "./supersearch.section";
export * from "./stats.section";
export * from "./reviews.section";
export * from "./notifications.section";
export * from "./lacite_astuces.section";
export * from "./nouveautes.section";
export * from "./goboard.section";
export * from "./favorites.section";
export * from "./hero";